INSERT INTO SOFTSKILL VALUES(1, 'Richting en sturing geven aan medewerkers in het kader van hun taakvervulling; stijl en methode van leidinggeven aanpassen aan betrokken medewerker/groep medewerkers en situatie.', 'Leidinggeven');
INSERT INTO SOFTSKILL VALUES(2, 'beter worden in Richting en sturing geven aan een medewerker in het kader van diens taakvervulling; stijl van coachen aanpassen aan medewerker en situatie zodat betrokken medewerker zich optimaal kan ontwikkelen.', 'Coachen');
INSERT INTO SOFTSKILL VALUES(3, 'beter worden in Richting en sturing geven aan een groep medewerkers in het kader van hun taakvervulling; samenwerkingsverbanden tot stand brengen en handhaven teneinde een gesteld doel te bereiken.', 'Groepsgericht Leidinggeven');
INSERT INTO SOFTSKILL VALUES(4, 'Eigen taken, beslissingsbevoegdheden en verantwoordelijkheden op duidelijke wijze toedelen aan de juiste medewerkers; effectief gebruik maken van tijd en vaardigheden van de medewerkers.', 'Delegeren');
INSERT INTO SOFTSKILL VALUES(5, 'Op effectieve wijze doelen en prioriteiten bepalen en benodigde tijd, acties en middelen aangeven om bepaalde doelen te kunnen bereiken.', 'Plannen en Organiseren');
INSERT INTO SOFTSKILL VALUES(6, 'Opstellen en bewaken van procedures om de voortgang van taken of activiteiten van medewerkers en van de eigen taken en verantwoordelijkheden te bewaken en zeker te stellen.', 'Voortgangsbewaking');
INSERT INTO SOFTSKILL VALUES(7, 'Signaleren en zakelijk afwegen van kansen in de markt zowel voor bestaande als nieuwe producten/ diensten; risico’s aangaan teneinde zakelijk voordeel te behalen.', 'Ondernemerschap');
INSERT INTO SOFTSKILL VALUES(8, 'Laten blijken goed geïnformeerd te zijn over ontwikkelingen in de markt en technologie.', 'Marktgerichtheid');
INSERT INTO SOFTSKILL VALUES(9, 'Onderzoeken van wensen en behoeften van de klant en hiernaar handelen. Anticiperen op behoeften van klanten. Hoge prioriteit geven aan servicebereidheid en klanttevredenheid.', 'Klantgerichtheid');
INSERT INTO SOFTSKILL VALUES(10, 'Het opbouwen van relaties en netwerken die van pas komen bij het realiseren van doelstellingen. Informele netwerken effectief aanwenden om zaken voor elkaar te krijgen.', 'Netwerken');
INSERT INTO SOFTSKILL VALUES(11, 'Signaleren van problemen; herkennen van belangrijke informatie; verbanden leggen tussen gegevens. Opsporen van mogelijke oorzaken van problemen; zoeken naar ter zake doende gegevens.', 'Probleemanalyse');
INSERT INTO SOFTSKILL VALUES(12, 'Op basis van beschikbare informatie juiste en realistische conclusies trekken.', 'Oordeelsvorming');
INSERT INTO SOFTSKILL VALUES(13, 'Beslissingen nemen door middel van het ondernemen van acties of zich vastleggen door middel van het uitspreken van oordelen.', 'Besluitvaardigheid');
INSERT INTO SOFTSKILL VALUES(14, 'Afstand nemen van de dagelijkse praktijk; zich concentreren op hoofdlijnen en beleid op de lange termijn.', 'Visie');
INSERT INTO SOFTSKILL VALUES(15, 'Onderkennen van invloed en gevolgen van eigen beslissingen of activiteiten op andere onderdelen van de organisatie; onderkennen van belangen van andere onderdelen van de eigen organisatie.', 'Organisatiesensitiviteit');
INSERT INTO SOFTSKILL VALUES(16, 'Laten blijken goed geïnformeerd te zijn over maatschappelijke, politieke en economische ontwikkelingen en deze kennis effectief benutten voor de eigen functie of organisatie.', 'Omgevingsbewustzijn');
INSERT INTO SOFTSKILL VALUES(17, 'Nieuwe informatie en ideeën in zich opnemen en effectief toepassen.', 'Leervermogen');
INSERT INTO SOFTSKILL VALUES(18, 'Met oorspronkelijke oplossingen komen voor problemen die met de functie verband houden. Nieuwe werkwijzen bedenken ter vervanging van bestaande', 'Creativiteit');
INSERT INTO SOFTSKILL VALUES(19, 'Effectief het eigen werk organiseren door het formuleren van doelstellingen en het plannen van activiteiten; beschikbare tijd en energie richten op de hoofdzaken en acute problemen.', 'Organiseren van eigen werk');
INSERT INTO SOFTSKILL VALUES(20, 'Ideeën en meningen aan anderen duidelijk maken, gebruik makend van duidelijke taal, gebaren en non-verbale communicatie. Taal en terminologie aanpassen aan anderen.', 'Mondelinge communicatie:');
INSERT INTO SOFTSKILL VALUES(21, 'Ideeën en feiten op heldere wijze presenteren, gebruik makend van terzake doende middelen. Presentatie afstemmen op de behoeften van het publiek.', 'Mondelinge presentatie');
INSERT INTO SOFTSKILL VALUES(22, 'Ideeën en meningen duidelijk maken in een rapport of document dat de juiste opzet en structuur heeft, grammaticaal correct is en dat de juiste taal en terminologie voor de lezer bevat.', 'Schriftelijke communicatie:');
INSERT INTO SOFTSKILL VALUES(23, 'Tonen belangrijke informatie op te pikken uit mondelinge mededelingen. Doorvragen; ingaan op reacties.', 'Luisteren');
INSERT INTO SOFTSKILL VALUES(24, 'Zich bewust tonen van andere mensen en de omgeving alsmede de eigen invloed hierop. Gedrag laten zien dat getuigt van het onderkennen van de gevoelens en behoeften van anderen.', 'Sensitiviteit');
INSERT INTO SOFTSKILL VALUES(25, 'Proberen anderen te overtuigen van een bepaald standpunt en trachten instemming te verkrijgen door gebruik te maken van de juiste argumenten en methode.', 'Overtuigingskracht');
INSERT INTO SOFTSKILL VALUES(26, 'Effectief communiceren van eigen standpunten en argumenten en het ontdekken en benoemen van gemeenschappelijke doelen op een wijze die tot overeenstemming en acceptatie bij beide partijen leidt.', 'Onderhandelen');
INSERT INTO SOFTSKILL VALUES(27, 'Een vertrouwenwekkende eerste indruk op anderen maken en deze weten te handhaven.', 'Impact');
INSERT INTO SOFTSKILL VALUES(28, 'Een actieve bijdrage leveren aan een gezamenlijk resultaat of probleemoplossing, ook wanneer de samenwerking een onderwerp betreft dat niet direct van persoonlijk belang is.', 'Samenwerken');
INSERT INTO SOFTSKILL VALUES(29, 'Zich zonder moeite onder andere mensen begeven. Gemakkelijk naar anderen toestappen en zich gemakkelijk in gezelschap mengen.', 'Sociabiliteit');
INSERT INTO SOFTSKILL VALUES(30, 'Doelmatig blijven handelen door zich aan te passen aan veranderde omstandigheden, taken, verantwoordelijkheden en/of mensen.', 'Aanpassingsvermogen');
INSERT INTO SOFTSKILL VALUES(31, 'Effectief blijven presteren onder tijdsdruk, bij tegenslag, teleurstelling of tegenspel.', 'Stressbestendigheid');
INSERT INTO SOFTSKILL VALUES(32, 'Acties ondernemen die meer gebaseerd zijn op eigen overtuiging dan op een verlangen om een ander een plezier te doen. Een eigen koers varen..', 'Onafhankelijkheid');
INSERT INTO SOFTSKILL VALUES(33, 'Bij een bepaald actieplan of opvatting blijven totdat het beoogde doel bereikt is of ophoudt redelijkerwijze bereikbaar te zijn.', 'Vasthoudendheid');
INSERT INTO SOFTSKILL VALUES(34, 'Indien zich problemen of kansen voordoen de eigen gedragsstijl veranderen teneinde het gestelde doel te bereiken.', 'Flexibel gedrag:');
INSERT INTO SOFTSKILL VALUES(35, 'ndien zich problemen of kansen voordoen de eigen gedragsstijl veranderen teneinde het gestelde doel te bereiken.', 'Initiatief');
INSERT INTO SOFTSKILL VALUES(36, 'tellen van hoge eisen aan het eigen werk en daarnaar handelen. Laten zien niet tevreden te zijn met een gemiddelde prestatie.', 'Inzet');
INSERT INTO SOFTSKILL VALUES(37, 'Gedrag vertonen dat erop gericht is hogerop te komen of meer verantwoordelijkheden te verkrijgen.', 'Ambitie');
INSERT INTO SOFTSKILL VALUES(38, 'Inzicht hebben in eigen sterktes en zwaktes. Op basis hiervan acties ondernemen om eigen kennis, vaardigheden en competenties te vergroten/verbeteren en zodoende beter te presteren.', 'Zelfontwikkeling');
INSERT INTO SOFTSKILL VALUES(39, 'Handhaven van algemeen aanvaarde sociale en ethische normen in activiteiten die met de functie te maken hebben.', 'Integriteit');
INSERT INTO SOFTSKILL VALUES(40, 'Zich voegen naar het beleid en/of de procedures van de organisatie. Bij onduidelijkheden of veranderingen bevestiging zoeken bij de juiste autoriteit.', 'Discipline');
INSERT INTO SOFTSKILL VALUES(41, 'Eigen gedrag in lijn brengen met de cultuur, behoeften, prioriteiten en doelen van de organisatie.', 'Organisatieloyaliteit');
INSERT INTO SOFTSKILL VALUES(42, 'Actief gericht zijn op het behalen van resultaten en doelstellingen en de bereidheid tonen om in te grijpen bij tegenvallende resultaten.', 'Resultaatgerichtheid');
INSERT INTO SOFTSKILL VALUES(43, 'Hoge eisen stellen aan kwaliteit van producten en diensten en daarnaar handelen.', 'Kwaliteitsgerichtheid');

INSERT INTO PERSONAL_SOFTSKILL VALUES(1, 'OMGAAN MET ANDEREN', 'SAMENWERKEN', 'BETER LEREN SAMENWERKEN', 'alexandra');

INSERT INTO PERSONAL_HARDSKILL VALUES(1, 'EEN PROGRAMEERTAAL', '2020-12-21', 'JAVA', 'JAVAJAVA', '2019-12-21', 'FINISHED', 'HENK');
INSERT INTO PERSONAL_HARDSKILL VALUES(2, 'EEN WERKMETHODE', '2020-12-22', 'SCRUM', 'SCRUMSCRUM', '2019-12-22', 'FINISHED', 'Simone');

INSERT INTO COURSE VALUES(1, 'EEN AGILE WERKMETHODE', 'SCRUM');
INSERT INTO COURSE VALUES(2, 'REQUIREMENTS ENGINEERINGING', 'IREB');
INSERT INTO COURSE VALUES(3, 'TESTING', 'ISTQB');